---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  install_strategy: always

verifier:
  name: inspec
  sudo: true
  inspec_tests:
  - test/integration/default

platforms:
- name: apex/macos-10.11.6
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

suites:
- name: default
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - updates-disabled

- name: default-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - updates-disabled

- name: power-management
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: power-management-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: machine-name
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: machine-name-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: spotlight
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing-and-searching

- name: spotlight-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing-and-searching

- name: xcode
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode-and-simulators

- name: xcode-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode-and-simulators

- name: xcode-beta
  provisioner:
    product_version:
    - 14
  includes:
  - apex/macos-10.13.3
  run_list:
  - recipe[macos_test::xcode_beta]
  verifier:
    controls:
    - xcode-beta

- name: xcode-beta-chef13
  provisioner:
    product_version:
    - 13
  includes:
  - apex/macos-10.13.3
  run_list:
  - recipe[macos_test::xcode_beta]
  verifier:
    controls:
    - xcode-beta

- name: certificate
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - certificate-install

- name: certificate-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - certificate-install

- name: users
  provisioner:
    product_version:
    - 14
  run_list:
  - recipe[macos_test::new_users]
  verifier:
    controls:
    - admin-user
    - standard-user

- name: users-chef13
  provisioner:
    product_version:
    - 13
  run_list:
  - recipe[macos_test::new_users]
  verifier:
    controls:
    - admin-user
    - standard-user
