name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - documentation/*
    - LICENSE
    - README.md
    - CHANGELOG.md
    - TESTING.md
    - CONTRIBUTING.md
    - .mailmap
    - .rubocop.yml
    - .gitignore
    - chefignore

pr:
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - documentation/*
    - LICENSE
    - README.md
    - CHANGELOG.md
    - TESTING.md
    - CONTRIBUTING.md
    - .mailmap
    - .rubocop.yml
    - .gitignore
    - chefignore

resources:
  repositories:
  - repository: templates
    type: git
    name: chef-pipelines-templates

jobs:
- template: chefspec-cookstyle-foodcritic.yml@templates
- template: test-kitchen.yml@templates
  parameters:
    platforms:
    - high-sierra-chef14
    - mojave-chef14
    - high-sierra-chef15
    - mojave-chef15
    suites:
    - default
    - software-updates
    - power-management
    - spotlight
    - xcode-from-apple
    - xcode-from-url
    - command-line-tools
    - certificate
    - users
    - delete-users
    - keychain
    - remote-access
    kitchenFile: kitchen.yml